[main]
path = "../models"


[biomarkers_April2013.remove_error]
skip = true     # Symbol Y defined after being used

[Executable_myelosuppression_dailyANC.remove_error]
skip = true     # Symbol EVID not defined

[Executable_OriginalModelCode256.remove_error]
skip = true     # Symbol DV not defined

[Executable_Paracetamol_Zebrafish_345dpf.remove_error]
skip = true     # Symbol A(2) not defined

[final_INH.remove_error]
skip = true     # Symbol Y defined after being used

[final_MXF.remove_error]
skip = true     # Symbol Y defined after being used

[final_PZA.remove_error]
skip = true     # Symbol Y defined after being used

[final_RIF.remove_error]
skip = true     # Symbol Y defined after being used

[Quartino-AL-2010-Docetaxel.remove_error]
skip = true     # Symbol Y defined after being used

[run1_clometh.remove_error]
skip = true     # Symbol CLINDU defined after being used

[run009.remove_error]
skip = true
error = "Symbol Y defined after being used"

[run42.remove_error]
skip = true     # Symbol DV not defined

[run49_cpt_neu.remove_error]
skip = true     # Symbol THETA(1) not defined

[run92.remove_error]
skip = true
error = "Symbol ICALL is not defined"

[run1230k.remove_error]
skip = true     # Symbol Y defined after being used

[run133.remove_error]
skip = true
error = "Symbol DOSTIM is not defined"

[run136a.remove_error]
skip = true     # Symbol A(2) not defined

[run159_cpt_wbc.remove_error]
skip = true     # Symbol THETA(1) not defined

[run164.remove_error]
skip = true     # Symbol Y defined after being used

[run168.remove_error]
skip = true     # Symbol Y defined after being used

[run189.remove_error]
skip = true
error = "Symbol Y defined after being used"

[run189_tomas.remove_error]
skip = true     # Symbol SIGMA(1) not defined

[run236.remove_error]
skip = true     # Symbol Y defined after being used

[run265.remove_error]
skip = true     # Symbol STRA not defined

[run119tf.remove_error]
skip = true     # Symbol Y defined after being used

[run40b.remove_error]
skip = true     # Symbol DV not defined 

[run649.remove_error]
skip = true     # ICALL not supported in update

[run649_clean.remove_error]
skip = true
error = "Symbol ICALL is not defined"

[run678.remove_error]
skip = true     # DOSTIM not supported in update

[run687.remove_error]
skip = true
error = "Symbol DOSTIM is not defined"

[run696b.remove_error]
skip = true     # Symbol CLRL not defined 

[run800.remove_error]
skip = true     # MIXNUM not supported in update

[run83_morphine.remove_error]
skip = true     # Symbol Y defined after being used

[run882.remove_error]
skip = true     # Symbol THETA(1) not defined

[run1004.remove_error]
skip = true     # Symbol Y defined after being used

[run1032_clean.remove_error]
skip = true
error = "Symbol DOSTIM is not defined"

[run2305.remove_error]
skip = true     # DOSTIM not supported in update

[run2305.remove_parameter_uncertainty_step]
skip = true

[Executable_Paracetamol_Zebrafish_345dpf.has_first_order_absorption]
skip = true
error = "Cannot find central compartment" 

[Executable_OriginalModelCode.has_first_order_absorption]
skip = true
error = "Cannot find central compartment" 

[Executable_ParacetamolInNewborns.has_first_order_absorption]
skip = true
error = "Cannot find central compartment" 

[run89_gupta.has_linear_odes_with_real_eigenvalues]
skip = true
error = "Takes more than 10s to run"

[run229.has_linear_odes_with_real_eigenvalues]
skip = true
error = "Error from sympy"

[Executable_OriginalModelCode.repr]
skip = true
error = "Cannot find central compartment"

[Executable_ParacetamolInNewborns.repr]
skip = true
error = "Cannot find central compartment"

[Executable_Paracetamol_Zebrafish_345dpf.repr]
skip = true
error = "Cannot find central compartment"

[Executable_ParacetamolInNewborns.has_first_order_elimination]
skip = true
error = "Cannot find central compartment"

[Executable_OriginalModelCode.has_first_order_elimination]
skip = true
error = "Cannot find central compartment"

[Executable_Paracetamol_Zebrafish_345dpf.has_first_order_elimination]
skip = true
error = "Cannot find central compartment"

[Executable_ParacetamolInNewborns.has_instantaneous_absorption]
skip = true
error = "Cannot find central compartment"

[Executable_OriginalModelCode.has_instantaneous_absorption]
skip = true
error = "Cannot find central compartment"

[Executable_Paracetamol_Zebrafish_345dpf.has_instantaneous_absorption]
skip = true
error = "Cannot find central compartment"
